#!/usr/bin/env zsh

for sub in {cdc_st,nvim_st,cdc_dwm}; do
    (builtin cd "$(dirname $0)/submodules/$sub"; make)
done

builtin cd "$(dirname $0)/system-config"

(find . -type f; find . -type l) | while builtin read file; do
    mkdir -p "$(dirname ~/${file})"
    ln -Trfs ${file} ~/${file}
done

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
