#!/usr/bin/env zsh

builtin cd "$(dirname $0)/system-config"

(find . -type f; find . -type l) | while builtin read file; do
    mkdir -p "$(dirname ~/${file})"
    ln -Trfs ${file} ~/${file}
done

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
