{-# LANGUAGE EmptyDataDecls, TypeSynonymInstances #-}
{-# OPTIONS_GHC -fcontext-stack43 #-}
---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DBInfo.Posts where

import Database.HaskellDB.DBLayout

---------------------------------------------------------------------------
-- Table type
---------------------------------------------------------------------------

type Posts =
    (RecCons Id (Expr Int)
     (RecCons Datetime_posted (Expr CalendarTime)
      (RecCons Content (Expr String) RecNil)))

---------------------------------------------------------------------------
-- Table
---------------------------------------------------------------------------
posts :: Table Posts
posts = baseTable "posts" $
        hdbMakeEntry Id #
        hdbMakeEntry Datetime_posted #
        hdbMakeEntry Content

---------------------------------------------------------------------------
-- Fields
---------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Id Field
---------------------------------------------------------------------------

data Id = Id

instance FieldTag Id where fieldName _ = "id"

xid :: Attr Id Int
xid = mkAttr Id

---------------------------------------------------------------------------
-- Datetime_posted Field
---------------------------------------------------------------------------

data Datetime_posted = Datetime_posted

instance FieldTag Datetime_posted where
    fieldName _ = "datetime_posted"

datetime_posted :: Attr Datetime_posted CalendarTime
datetime_posted = mkAttr Datetime_posted

---------------------------------------------------------------------------
-- Content Field
---------------------------------------------------------------------------

data Content = Content

instance FieldTag Content where fieldName _ = "content"

content :: Attr Content String
content = mkAttr Content
