#!/usr/bin/env zsh

function usage {
    echo "usage: $(basename $0)" 1>&2
    echo "       $(basename $0) cli" 1>&2
    echo "       $(basename $0) X" 1>&2
}

repo_core=$(dirname "$(realpath $0)")
config_src=$(realpath ${repo_core}/../system-config)
cli_src=${config_src}/cli-files
X_src=${config_src}/X-files
dev_src=${config_src}/dev

function link-cli {
    link_from_home=(.emacs .haskeline .inputrc .pyinputrc .tmux.conf .vimrc
                    .zprofile .zsh_aliases .zsh_autoload .zshenv .zshrc .ghci
                    .vim .zsh .rtorrent.rc .latexmkrc .irbrc .screenrc)

    builtin cd
    rm ${link_from_home} 2> /dev/null

    for file in ${link_from_home}; do
        ln -s ${cli_src}/${file}
    done
}

function link-X {
    link_from_home=(.xbindkeysrc .xinitrc .xmobarrc .Xmodmap .xprofile
                    .Xresources)

    builtin cd
    rm ${link_from_home} 2> /dev/null

    if [[ ! -e ${HOME}/.xmonad ]]; then
        mkdir ${HOME}/.xmonad
    fi
    rm ${HOME}/.xmonad/xmonad.hs 2> /dev/null

    for file in ${link_from_home}; do
        ln -s ${X_src}/${file}
    done

    if [[ ! -e ${HOME}/.xmonad ]]; then
        mkdir ${HOME}/.xmonad
    fi
    builtin cd ${HOME}/.xmonad
    rm xmonad.hs 2> /dev/null

    ln -s ${X_src}/xmonad.hs
}

function link-dev {
    builtin cd
    rm .dev
    ln -s ${dev_src} .dev
}

if [[ $# -eq 1 ]]; then
    case $1 in
        (cli)
            link-cli
            ;;
        (X)
            link-X
            ;;
        (dev)
            link-dev
            ;;
        (*)
            usage
            exit 1
            ;;
    esac
elif [[ $# -eq 0 ]]; then
    link-cli
    link-X
    link-dev
else
    usage
    exit 1
fi
