#!/bin/bash

list=$(find ${HOME}/media/music/sabers -mindepth 1)
num=$(echo "${list}" | wc -l)

chosenNum=$(((RANDOM % num) + 1))
chosenFile=$(find ${HOME}/media/music/sabers | head -${chosenNum} | tail -1)

mplayer "${chosenFile}"
