#!/bin/bash

if [[ ! -v BACKUP_DIR ]]; then
    BACKUP_DIR="${HOME}/utilities/backups"
fi

if [[ ! -e "${BACKUP_DIR}" ]]; then
    echo "ERROR: non-existent backups directory: ${BACKUP_DIR}" 1>&2
    echo "If this isn't where your backups are, export the correct definition \
of BACKUP_DIR and run again" 1>&2
    exit 1
fi

for filename in "$@"; do
    file_basename=$(basename "${filename}")
    backupName=${file_basename/#./dot_}
    backupsList=$(find "${BACKUP_DIR}" -regextype posix-extended \
        -regex ".*/$(${HOME}/utilities/scripts/ex-escape-meta "${backupName}")-[0-9]{4}-[0-9]{2}-[0-9]{2}__([0-9]{2}-){2}[0-9]{2}\.bak")

    if [[ -z "${backupsList}" ]]; then
        echo "ERROR: no backups found for ${filename}" 1>&2
        echo "${filename} was not backed up. Continuing..."
        continue
    fi

    mostRecentBackup=$(echo "${backupsList}" | sort | tail -1)
    cp "${mostRecentBackup}" "${filename}"
done
