#!/bin/bash

if [[ -n ${DISPLAY} || ${zsh_parent_process} == "sshd" ]]; then
    echo -ne '\e[1 q'
else
    echo -ne '\e[?6c'
fi
vim "$@"

optionRegex='^-.*$'
for arg in "$@"; do
    if [[ ! "${arg}" =~ ${optionRegex} && -e "${arg}" && ! -x "${arg}" ]]; then
        chmod +x ${arg}
    fi
done

exit 0
