---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module DBInfo where

import Database.HaskellDB.DBLayout

import qualified DBInfo.Posts

cdchawth :: DBInfo
cdchawth = DBInfo {dbname = "cdchawth",
                   opts = DBOptions {useBString = False},
                   tbls = [TInfo {tname = "posts",
                                  cols = [CInfo {cname = "id",
                                                 descr = (IntT, False)},
                                          CInfo {cname = "datetime_posted",
                                                 descr = (CalendarTimeT, False)},
                                          CInfo {cname = "content",
                                                 descr = (StringT, False)}]}]}