#!/usr/bin/env zsh

if [[ $# -eq 0 ]]; then
    dst=lines_array
else
    dst=$1
fi

eval "${dst}=()"
local "${dst}_line"
while builtin read "${dst}_line"; do
    eval "${dst}=(\${${dst}} \${${dst}_line})"
done
