#!/usr/bin/env zsh

volExp='s_^.*\[(.*)%\].*$_\1_g'
muteExp1='s_^.*\[on\]$_Unmuted_g' 
muteExp2='s_^.*\[off\]$_Muted_g'

function safe_osd_cat {
    pkill osd_cat
    osd_cat $*
}

case $1 in
    (toggleMute)
        msg=$(amixer set Master toggle | tail -n 1 | sed -r -e ${muteExp1} -e ${muteExp2})
        font='-*-Fixed-Bold-R-Normal-*-13-*-*-*-*-*-*-*'
        safe_osd_cat -d 2 -c cyan -A center -o 3 -i 215 -f ${font} <<< ${msg}
        ;;
    (raise)
        percentage=$(amixer set Master playback ${2}+ | tail -n 1 | sed -re ${volExp})
        safe_osd_cat -d 2 -c cyan -A center -o 3 -b percentage -P $percentage
        ;;
    (lower)
        percentage=$(amixer set Master playback ${2}- | tail -n 1 | sed -re ${volExp})
        safe_osd_cat -d 2 -c cyan -A center -o 3 -b percentage -P ${percentage}
        ;;
}
