#!/usr/bin/env zsh

if [[ -z ${BACKGROUNDS_FILE} ]]; then
    BACKGROUNDS_FILE=${HOME}/.backgrounds
fi

feh_bg_flag="--bg-center"

for background in $@; do
    feh ${feh_bg_flag} ${background}
    echo "Enter y to add to user's backgrounds file"
    read isGood
    if [[ ${isGood} == y ]]; then
        realpath ${background} >> ${BACKGROUNDS_FILE}
    fi
done
