#!/usr/bin/env zsh

if [[ -z ${BACKGROUNDS_FILE} ]]; then
    BACKGROUNDS_FILE=${HOME}/.backgrounds
fi

if [[ ! -e ${BACKGROUNDS_FILE} ]]; then
    echo "ERROR: non-existent backgrounds file: ${BACKGROUNDS_FILE}" 1>&2
    echo "If this isn't your backgrounds file, export the correct definition of \
BACKGROUNDS_FILE and run again."
    exit 1
fi

temp_file="$(mktemp)"

for file in $@; do
    fgrep -vx "$(realpath ${file})" ${BACKGROUNDS_FILE} > ${temp_file}
    cp ${temp_file} ${BACKGROUNDS_FILE}
done
