#!/usr/bin/env zsh

if [[ -z ${BACKGROUNDS_FILE} ]]; then
    BACKGROUNDS_FILE=${HOME}/.backgrounds
fi

if [[ ! -r ${BACKGROUNDS_FILE} ]]; then
    echo "ERROR: non-existent or non-readable backgrounds file: ${BACKGROUNDS_FILE}" 1>&2
    echo "If this isn't your backgrounds file, export the correct definition of \
BACKGROUNDS_FILE and run again."
    exit 1
fi

feh_bg_flag="--bg-center"

num="$(wc -l < ${BACKGROUNDS_FILE})"

chosenNum=$(((RANDOM % num) + 1))
chosenFile=$(head -${chosenNum} ${BACKGROUNDS_FILE} | tail -1)

feh ${feh_bg_flag} ${chosenFile}
