#!/usr/bin/env zsh

font='-*-Fixed-Bold-R-Normal-*-13-*-*-*-*-*-*-*'

function safe_osd_cat {
    pkill osd_cat
    osd_cat $*
}

if egrep '^(mode:[[:blank:]]*)off$' ~/.xscreensaver &> /dev/null; then
    sed -ri -e 's/^(mode:[[:blank:]]*)off$/\1blank/g' ~/.xscreensaver
    msg="Screensaver on"
    safe_osd_cat -d 2 -c cyan -A center -o 3 -i 215 -f ${font} <<< ${msg}
elif egrep '^(mode:[[:blank:]]*)blank$' ~/.xscreensaver &> /dev/null; then
    sed -ri -e 's/^(mode:[[:blank:]]*)blank$/\1off/g' ~/.xscreensaver
    msg="Screensaver off"
    safe_osd_cat -d 2 -c cyan -A center -o 3 -i 215 -f ${font} <<< ${msg}
fi
